[Interface]
PrivateKey = qEEV/P8i+6b1+YrO8tNAlWwJzga/vIwQsXHs27ajcX0=
Address = 10.2.0.2/32
Table = off
FwMark = 51820
PostUp = /opt/wg-up.sh %i
PreDown = /opt/wg-down.sh %i

[Peer]
# FI#12
PublicKey = cdx8bADYVWBlHkg6Ekl6k2y0kjkYNFagN2ttPC128HU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 196.196.203.202:51820
PersistentKeepalive = 25
